# Generated by Django 5.0.1 on 2024-03-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
