# Generated by Django 5.0.1 on 2024-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colors',
            field=models.ManyToManyField(blank=True, to='store.color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size'),
        ),
    ]
