# Generated by Django 5.0.1 on 2024-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_colors_orderitem_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='store.size'),
        ),
    ]
