# Generated by Django 5.0.1 on 2024-03-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.size'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
